### PR TITLE
Added joy and joystick_teleop packages

### PR DESCRIPTION
**Pull request by Musi13**
"joy" is a public library package to enable joystick compatibility with ROS. "joystick_teleop" is a new package to allow joystick control of the robots. There is a roslaunch file included in the joystick_teleop package which can be started with "roslaunch joystick_teleop joystick_teleop.launch".

The following is an excerpt from joystick_teleop's README file:
Controls are as follows:
-"Tank Drive" The left stick forward and back provides positive and negative linear.x movement while
    the right stick right and left provide positive and negative angular.z movement.
-Using the directional pad allows the user to change the speed multipliers. Up on the D-pad increases
    the linear multiplier, while down decreases it. Right on the D-pad increases the angular (turning)
    multiplier, while left decreases it.
-Pressing/Holding the "B" button (the red button on the right side of xbox 360 controllers) will send
    a constant stream of 0 velocity commands until released. This is used as an emergency stop.

### CODE REVIEW

**Comment by jack-oquin** [comment]
I don't think we need or want our own copy of the ``joy`` package. It's already included in the standard ROS drivers, and source is here:

* https://github.com/ros-drivers/joystick_drivers

The ``joy_teleop`` package should simply depend on that.

Where did ``joy_teleop`` come from?

**Comment by Musi13** [comment]
I've removed the copy of the joy library; it was in there because I didn't know it was a part of the standard ROS library. Also, joystick_teleop is a package I have written.

**Comment by jack-oquin** [comment]
That's good, Alex, thanks. 

Could you please add a copyright notice for your code and a license in the package.xml? The preferred license is BSD, and an example C++ copyright and license comment is here:

 * https://github.com/utexas-bwi/segbot/blob/master/segbot_sensors/src/sonar/range_nodelet.cpp

**Comment by Musi13** [comment]
Updated; I apologize for not having these things done. I've never submitted formal code before.

**Comment by jack-oquin** [comment]
No worries, and congratulations: you are now a full-fledged open-source contributor!

Thanks for doing this.

**Pull request merged**
